### ISSUE TITLE
Warning in CMake Configure step

### ISSUE THREAD

**Issue by ezavada** [slembcke/Chipmunk2D#100]
Configuring Chipmunk Library...
-- The C compiler identification is AppleClang 6.0.0.6000056
-- The CXX compiler identification is AppleClang 6.0.0.6000056
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Configuring Chipmunk2D version 7.0.0
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   chipmunk

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/ezavada/work/pdg/build/darwin/chipmunk

The issue is addressed by adding the following line near the top of CMakeLists.txt:

    cmake_policy(SET CMP0042 NEW) # use MACOSX_RPATH

**Comment by slembcke** [comment]
91149ed
