### ISSUE TITLE
Visual Studio Error: _USE_MATH_DEFINES redefinition

### ISSUE THREAD

**Issue by DeeKayHT** [slembcke/Chipmunk2D#101]
Currently some build configurations in Visual Studio 2012 and 2013 are failing to compile due to _USE_MATH_DEFINES being redefined.  The cause of this is due to chipmunk.h defining it for Visual Studio compilers on line 26 and certain configurations having it also set in the Project Setting's: Property > C/C++ > Preprocessor > Preprocessor Definitions

Right now I'm going through fixing the redefinition error, but I'd like some feedback on how you prefer this fix to be made.  Would you prefer the code to handle defining _USE_MATH_DEFINES or would you prefer Visual Studio's project settings to do so?

**Comment by slembcke** [comment]
bde6116

Fixed by removing references to `M_PI` so that `_USE_MATH_DEFINES` is not required.
