### ISSUE TITLE
NEON vector optimization does not improve the performance...

### ISSUE THREAD

**Issue by spacelan** [slembcke/Chipmunk2D#103]
The NEON vector optimization do improve the performance if I compile the code without compiler optimization. But if I compile the code with compiler optimization, the performance is just equal to the original code.

In this blog http://howlingmoonsoftware.com/wordpress/chipmunk-pro-goes-neon-19-40-faster/, slembcke said he got a 40% speedup using the NEON vector optimization. This result is similar to the result that I compile code without compiler optimization.

So, I want to know whether slembcke compiled the code using compiler optimization and how he tested the demo.

**Comment by spacelan** [comment]
I use the command below to compile the code:
`arm-linux-gnueabihf-gcc  -static -Wall -mfpu=neon  -std=gnu99 -O1`
and run the demo on my arm-based android device shell:
`./demo -trial`

**Comment by slembcke** [comment]
I guess it really depends on the CPU. It made a big difference on older iOS devices with ARMv7 or ARMv7s CPUs. On Apple's new 64 bit A7 or A8 CPU it doesn't seem to make any difference for 32 bit floats. I'm not sure if it's the compiler or just that the newer CPU is that much more efficient at taking advantage of super scalar magic.

Without profiling at a very low level on a dozen different CPUs, I'm not quite sure how to know for sure why it doesn't get a nice speedup.
