### ISSUE TITLE
Visual Studio .def exports file needs to be updated (or use __declspec)

### ISSUE THREAD

**Issue by ewmailing** [slembcke/Chipmunk2D#105]
The exports .def file is extremely out of date. This is needed to correctly build dynamic libraries on Windows.

This is a continuing problem. It would be nice if you started using __declspec hidden behind macros to annotate which APIs are public/exported directly in the header files. This would also have the added benefit of being reusable for gcc/clang which have visibility attributes which restrict which APIs to export (which can shrink the binary and speed up link times).

**Comment by slembcke** [comment]
Adding them using macros is a really good point. In the past I avoided them because they made the headers "ugly". That's why I used to do the .def file, but you are right that it really is a problem.

**Comment by slembcke** [comment]
7f8d668
