### ISSUE TITLE
Use CMAKE as the only  build system 

### ISSUE THREAD

**Issue by thejinchao** [slembcke/Chipmunk2D#106]
It would be perfect if you remove MSVC projects and use CMAKE as the only build system on Windows/Linux/Mac.

**Comment by slembcke** [comment]
I personally like using the Xcode project to develop Chipmunk, and many many people have requested MSVC projects. This would definitely be a step backwards for a lot of users. Cmake can create Xcode/MSVC projects, but their structure is *awful*. I'm not quite sure I understand why that feature exists.
