### ISSUE TITLE
No tag for Chipmunk 7

### ISSUE THREAD

**Issue by jhasse** [slembcke/Chipmunk2D#107]
I can't find a tag or branch for Chipmunk 7.

Btw: Does a migration guide for 6 to 7 exist somewhere?

**Comment by slembcke** [comment]
https://github.com/slembcke/Chipmunk2D/tree/Chipmunk-7.0.0

**Comment by jhasse** [comment]
Thanks!

Regarding my question: I guess no?

**Comment by slembcke** [comment]
Oh. I missed the migration guide question. There isn't a guide yet. I guess it would probably be a good idea to make one though... I feel bad that I don't have as much time as I used to to work on Chipmunk. :-\

**Comment by jhasse** [comment]
No problem! You've already done an amazing job :)
