### ISSUE TITLE
Hello Chipmunk example not compiling

### ISSUE THREAD

**Issue by mantognini** [slembcke/Chipmunk2D#110]
Hi,

The first example displayed [here](http://chipmunk-physics.net/release/ChipmunkLatest-Docs/) has two issues when compiling it as a C++ program (haven't tried as a C program).

The first issue is just a few typos:
  * `cpBodySetPos` should be `cpBodySetPosition`
  * `cpBodyGetPos` should be `cpBodyGetPosition`
  * `cpBodyGetVel` should be `cpBodyGetVelocity`

But the other issue is more tricky and got only a workaround ATM: when compiling it as is, I get the following error

```
main.cpp:30:46: error: member access into incomplete type 'cpSpace'
    cpShape *ground = cpSegmentShapeNew(space->staticBody, cpv(-20, 5), cpv(20, -5), 0);
                                             ^
```

If I change the include to `#include <chipmunk_private.h>` it works but that's probably not how it should be solved...

**Comment by slembcke** [comment]
Bwa. I never updated those inline snippets for Chipmunk 7. You should use `cpSpaceGetStaticBody()` to get the builtin static body for the space. I'm about to head out on a two week vacation, but I'll fix this when I get back!

**Comment by mantognini** [comment]
Thanks for the quick reply, I'll try that.

Enjoy your holiday then ;)

**Comment by mantognini** [comment]
Yep, that works!

**Comment by slembcke** [comment]
Clean up day on Chipmunk. I need to do this more often. :-\
f5e696c548ac72fd9215bd538053a16247bbf0e8
