### ISSUE TITLE
CP_ALLOW_PRIVATE_ACCESS removed from ObjectiveChipmunk

### ISSUE THREAD

**Issue by killerham** [slembcke/Chipmunk2D#113]
When trying to update chipmunk submodule from cocos2d due to a 64bit issue, there were a bunch of errors because 

A) Files within the ObjectiveChipmunk folder like ChipmunkBody.m, ChipmunkShape.m, etc. were removed from the Chipmunk XCode project compile sources
B) CP_ALLOW_PRIVATE_ACCESS flag was removed, which stopped including the chipmunk/chipmunk_private.h

I temporarily fixed this issue by importing chipmunk_private.h file into the classes that required it, and added the necessary ObjectiveChipmunk files back into the compile sources of the Chipmunk project. This is probably not the best solution to this problem which is why I am posting this as an issue.

Thanks

**Comment by slembcke** [comment]
I fixed this in master by moving the struct definitions to a new header so that they can be included separately from the private functions.

Thanks!
