### ISSUE TITLE
Small issue with Xcode 7 

### ISSUE THREAD

**Issue by KAMIKAZEUA** [slembcke/Chipmunk2D#114]
I just downloaded Chipmunk from here and run example in Xcode 7, as result I see issue in cpSpatialIndex.h: - ../Chipmunk-7.0.1/include/chipmunk/cpSpatialIndex.h:57:5: Unknown command tag name.

/// @private
So, I just changed it to 
// @private
and it compiles ok. Xcode 7.1.1

**Comment by slembcke** [comment]
It's fixed in the master branch (I think). I should probably make another tag.

**Comment by gr8bit** [comment]
+1, just ran into that error :)
