### ISSUE TITLE
Xcode scheme for tvos

### ISSUE THREAD

**Issue by oxeron** [slembcke/Chipmunk2D#124]
Hi, 

I'm working on making cocos2d 3.5 work inside SpriteBuiler 1.5
I would need a twos scheme for chipmunk so that I can point directly to your repository
Do you think this is possible ?

Thank you

Olivier

**Comment by KAMIKAZEUA** [comment]
@slembcke  Any news?

**Comment by slembcke** [comment]
Err, hey guys. Sort of forgot about this.

We borrowed our Apple TV to another local dev since we hadn't been using it. That makes it somewhat awkward for me to add a tvos target since I can only test on the simulator. If you made a pull request that would help a lot. I think it should be as easy as duplicating the iOS target and changing the SDK, but I don't remember exactly.

**Comment by oxeron** [comment]
Hi, I can't push you a request, I did some other modifications in my repo here:

https://github.com/slembcke/Chipmunk2D/compare/master...oxeron:master

changed some iOS target version, removed ChipmunkDemo and some other minor changes, so that SpriteBuilder (now CocosBuilder) users get a clean project. I guess you don't want those modifications in your repo.

**Comment by slembcke** [comment]
Not really no. It is possible to select which targets/schemes in a subproject to show in the parent project's list. Bring up the scheme editor (command - <), then click "Manage Schemes" at the bottom. You can uncheck everything that the user won't actually run (dependencies don't need to be in that list). The sharing options should make it possible to put them into a template project.

**Comment by oxeron** [comment]
The problem is I want those schemes in SB but not in the template project created. And those two use the same cocos2d xcodeproj, so the same schemes are displayed in both for the moment. Am I right ?

**Comment by slembcke** [comment]
Not exactly sure I understand, but the parent project is the one that controls which schemes are shown. So you can hide the unused extra Chipmunk targets in the template project while leaving them in the SB project.

**Comment by oxeron** [comment]
mm ok I'll see if I can get this done, thank you for your help. May need some more on the cocos2d forum if you happen to come visit us someday. Your opinion would be very helpful for us :)

**Comment by oxeron** [comment]
Just send you a PR for tvOS
