### ISSUE TITLE
tags/7.0.1: include <sys/sysctl.h> - unneeded, breaks win32 compilation

### ISSUE THREAD

**Issue by antidotcb** [slembcke/Chipmunk2D#130]
Remove `#include <sys/sysctl.h>` from `cpHastySpace.c` at tags/7.0.1 please.
Otherwise it's not cross-platform and gives compile errors on windows.
Thanks.

**Comment by blazewicz** [comment]
This was already discussed in #99 and there is a pending PR for this: #109.

Let this issue be a gentle ping for @slembcke.

**Comment by slembcke** [comment]
Merged #109. A better fix will come... someday. :-\
