### ISSUE TITLE
Chipmunk demos can't be compiled in Ubuntu 16.10

### ISSUE THREAD

**Issue by NicholasShatokhin** [slembcke/Chipmunk2D#141]
I have glfw3 installed that newer than version needed for Chimpmunk demos and a bit differ. So, I can't configure and build it:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLFW_INCLUDE_DIR
   used as include directory in directory /home/robotex/sources/Chipmunk2D/demo

There is no older versions of GLFW in repository.

**Comment by NicholasShatokhin** [comment]
/home/robotex/sources/Chipmunk2D/demo/ChipmunkDebugDraw.c:26:21: fatal error: GL/glfw.h: No such file or directory
 #include "GL/glfw.h"

Path should be GLEW/glfw3.h
But some functions differ.

**Comment by saqib1707** [comment]
To the developers , I also got a similar error as mentioned above  while trying to configure Chipmunk-7.0.1
The log file is [here](http://pastebin.com/zpdg5SiD)

I have uploaded  the CMakeOutput.log file [here](http://pastebin.com/DUbrZaUm).
Please consider this problem and help us!!

**Comment by Gratiandev** [comment]
Did you run 
`sudo apt install libglew-dev libglfw-dev freeglut3-dev`
?

**Comment by slembcke** [comment]
Should be fixed finally as the demos no longer rely on GLFW or GLEW.
