### ISSUE TITLE
cmake giving error while configuring chipmunk-7.0.1

### ISSUE THREAD

**Issue by saqib1707** [slembcke/Chipmunk2D#143]
After downloading chipmunk I tried to run the following commands- 
cmake -D CMAKE_BUILD_TYPE=Debug .
make

Here is the output  log which I got - 

Configuring Chipmunk2D version 7.0.1
**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:**
GLEW_INCLUDE_DIR
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
GLEW_LIBRARIES
    linked by target "chipmunk_demos" in directory /home/saqib1707/Chipmunk-7.0.1/demo
GLFW_INCLUDE_DIR
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
   used as include directory in directory /home/saqib1707/Chipmunk-7.0.1/demo
GLFW_LIBRARIES
    linked by target "chipmunk_demos" in directory /home/saqib1707/Chipmunk-7.0.1/demo

-- Configuring incomplete, errors occurred!
See also "/home/saqib1707/Chipmunk-7.0.1/CMakeFiles/CMakeOutput.log".

I am not able to resolve this  issue. I will be highly thankful if anyone can look into this issue and come up with a way to resolve this.

**Comment by saqib1707** [comment]
@slembcke I read there was a similar error posted on chipmunk forum . I have already installed **_glut and libxmu_** packages but still it is giving this error.. Can u please help me out since I cannot proceed on my project until I get rid of this error.? Thanks.

**Comment by saqib1707** [comment]
Is this  the right place to ask questions or should I ask on chipmunk forum ?

**Comment by pascalicious** [comment]
On Ubuntu I installed glfw and glew and the demos built fine
`sudo apt install libglfw-dev libglew-dev`

Not glfw3!

Also, if you edit the CMakeListst.txt and turn off the demo build you still get the library built.

**Comment by sbianti** [comment]
I still see this error: I installed glew-devel glfw-devel and only the GLEW_* and GLFW_LIBRARIES errors went away, still remains the GLFW_INCLUDE_DIR error.
Anybody from the developer team can help ?
