### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by pascalicious** [slembcke/Chipmunk2D#144]
In cpBodySetMass, cpBody.c, there is a division by zero when it is called from cpSpaceInit. Line 261 `body->m_inv = 1.0f/mass` The 'mass' has value 0.0f when called from cpSpaceInit in cpSpace.c at line 173, `cpBody *staticBody = cpBodyInit(&space->_staticBody, 0.0f, 0.0f)`

In C(99) the behaviour of division by zero is undefined.

**Comment by pascalicious** [comment]
C/C++ fpu exceptions are disabled by default, this issue was caught when working on a Delphi/Object Pascal translation of the header files. I'm able to work around this by disabling fpu exception checks before calling the library and then enabling them again, but it's sort of an ugly hack

**Comment by stolk** [comment]
I hit the same issue.
I fixed it by explicitly setting it to infinity, instead of dividing by zero.
I like to run my code with NaN exceptions enabled.
You can use this:

```
bram@ubuntu64:~/src/Chipmunk2D/src$ git diff cpBody.c
diff --git a/src/cpBody.c b/src/cpBody.c
index a8e0797..8ad2bc9 100644
--- a/src/cpBody.c
+++ b/src/cpBody.c
@@ -258,7 +258,7 @@ cpBodySetMass(cpBody *body, cpFloat mass)
        
        cpBodyActivate(body);
        body->m = mass;
-       body->m_inv = 1.0f/mass;
+       body->m_inv = mass == 0.0f ? INFINITY : 1.0f/mass;
        cpAssertSaneBody(body);
 }
 
@@ -275,7 +275,7 @@ cpBodySetMoment(cpBody *body, cpFloat moment)
        
        cpBodyActivate(body);
        body->i = moment;
-       body->i_inv = 1.0f/moment;
+       body->i_inv = moment == 0.0f ? INFINITY : 1.0f/moment;
        cpAssertSaneBody(body);
 }
```

**Comment by stolk** [comment]
I created pull request for this fix, at:
https://github.com/slembcke/Chipmunk2D/pull/163
