### ISSUE TITLE
error: comparing floating point with == or != is unsafe [-Werror=float-equal] (strict compiler checks)

### ISSUE THREAD

**Issue by dagostinelli** [slembcke/Chipmunk2D#149]
When compiling (my own code) with -Wfloat-equal, a number of instances pop up in the Chipmunk headers where there is a floating point equals in the code. 

Example in cpBB.h:
`if(delta.y == 0.0f){`

On the one hand, as a new user of the library, I find that curious, but I tend to imagine that with such a popular library, and so many folks using it, this is not a problem.  On the other hand, I'm curious why/how it is not a problem.   How it is that the floating point irregularities aren't affecting the library?

Here's another example from cpVect.h
`return (v1.x == v2.x && v1.y == v2.y);`

**Comment by slembcke** [comment]
Sorry for the late reply. Trying to clear out the issue backlog.

There are a number of places where I compare floating point numbers directly in Chipmunk, but generally speaking they are things like clamping a value to [0, 1], then checking if the value is 0. The example you posted above is avoiding a specific divide by zero case, and in the cpveql() case, it's exactly as "dangerous" as comparing floats. ;)
