### ISSUE TITLE
Contacts for sleeping bodies are leaked.

### ISSUE THREAD

**Issue by slembcke** [slembcke/Chipmunk2D#15]
They don't get freed when the space is deallocated. Need to wake up all the sleeping components before destroying. Fortunately it's only a hundred bytes or so every few seconds.

I could swear I've fixed this before...

**Comment by grimaldini** [comment]
I've been working on Xcode and it has detected that this might still be happening. I see several instances of leaking memory originating at https://github.com/slembcke/Chipmunk2D/blame/edf83e5603c5a0a104996bd816fca6d3facedd6a/src/cpSpaceComponent.c#L101. They seem to be happening when a body comes to rest and sleep time threshold has been set with `cpSpaceSetSleepTimeThreshold(space, 1.0f)`.

I am also attaching a screenshot with the malloc backtrace for the allocation in case it helps.
<img width="309" alt="Screen Shot 2022-07-01 at 3 17 58 AM" src="https://user-images.githubusercontent.com/653273/176877791-807a8f04-faa3-48b0-8cab-d1f783f05820.png">
