### ISSUE TITLE
Unexpected collision resolution with multiple static shapes

### ISSUE THREAD

**Issue by JoelBesada** [slembcke/Chipmunk2D#158]
I've noticed an issue when colliding with multiple static objects at the same time, and reduced it down to a simple case as seen in this video https://gfycat.com/gifs/detail/CommonRecentCentipede. 

![case](https://thumbs.gfycat.com/CommonRecentCentipede-size_restricted.gif)

The expected outcome is for the ball to bounce to the right instead of straight up on the first contact. This behavior makes it hard to build complex terrain that works well, because a concave shape needs to be decomposed into stitched together convex polygons, and every seam that this creates makes the above case more likely to happen. 

I created this as a demo, here's the source code for it:
```c
#include "chipmunk/chipmunk.h"
#include "ChipmunkDemo.h"

static cpBody *ballBody;

static void
update(cpSpace *space, double dt)
{
	cpSpaceStep(space, dt);
}

static cpSpace *
init(void)
{
	cpSpace *space = cpSpaceNew();
	cpSpaceSetIterations(space, 30);
	cpSpaceSetGravity(space, cpv(0, -800));
	cpSpaceSetCollisionSlop(space, 0.5);
	cpSpaceSetSleepTimeThreshold(space, 1.0f);
	
	cpBody *body, *staticBody = cpSpaceGetStaticBody(space);
	cpShape *shape;
	
	cpVect poly[3] = {cpv(-100, 0), cpv(0, -50), cpv(0, -150)};
	shape = cpSpaceAddShape(space, cpPolyShapeNew(staticBody, 3, poly, cpTransformIdentity, 1.0f));
	cpShapeSetElasticity(shape, 1.0f);
	cpShapeSetFriction(shape, 0.9f);
	
	cpVect poly2[3] = {cpv(0, -50), cpv(100, -75), cpv(0, -150)};
	shape = cpSpaceAddShape(space, cpPolyShapeNew(staticBody, 3, poly2, cpTransformIdentity, 1.0f));
	cpShapeSetElasticity(shape, 1.0f);
	cpShapeSetFriction(shape, 0.9f);
	
	cpFloat radius = 15.0f;
	ballBody = cpSpaceAddBody(space, cpBodyNew(10.0f, cpMomentForCircle(10.0f, 0.0f, radius, cpvzero)));
	cpBodySetPosition(ballBody, cpv(0, 100));
	cpBodySetVelocity(ballBody, cpv(0, -500));

	shape = cpSpaceAddShape(space, cpCircleShapeNew(ballBody, radius, cpvzero));
	cpShapeSetElasticity(shape, 0.5f);
	cpShapeSetFriction(shape, 0.5f);
	
	return space;
}

static void
destroy(cpSpace *space)
{
	ChipmunkDemoFreeSpaceChildren(space);
	cpSpaceFree(space);
}

ChipmunkDemo MulticontactIssue = {
	"Multicontact Issue",
	1.0/60.0,
	init,
	update,
	ChipmunkDemoDefaultDrawImpl,
	destroy,
};
```

**Comment by ghostserver10** [comment]
Hey. Have you found solution?

**Comment by JoelBesada** [comment]
@ghostserver10 not really, but I wrote about a workaround that I ended up using instead to avoid these scenarios: https://medium.com/@JoelBesada/swang-development-log-fixing-janky-collisions-f84bf4b285e5

**Comment by slembcke** [comment]
Add a smoothing radius to the polygons. Even a few pixels is going to help tremendously.
