### ISSUE TITLE
Building for Android using CMake

### ISSUE THREAD

**Issue by waj334** [slembcke/Chipmunk2D#159]
The is a header issue when building on Android in cpHastySpace.c :
#ifndef _WIN32
#include <sys/sysctl.h>
#include <pthread.h>
#else
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

**I changed to this and it now works**:

#ifndef _WIN32
#ifdef __APPLE__
#include <sys/sysctl.h>
#elif __ANDROID__
#include <linux/sysctl.h>
#endif
#include <pthread.h>
#else
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

**also it couldn't link the log lib as well so I made the following change in src/CMakeLists.txt:**
if(NOT ANDROID)
    set_target_properties(chipmunk PROPERTIES
      SOVERSION ${CHIPMUNK_VERSION_MAJOR}
      VERSION ${CHIPMUNK_VERSION})
  else()
    find_library(log-lib log )
    target_link_libraries(chipmunk ${log-lib})
endif()

**Comment by slembcke** [comment]
I think this has finally been fixed? I haven't dealt with mobile dev for a few years though.

**Comment by jhasse** [comment]
Yeah I think so, builds fine for me with the latest Android NDK.
