### ISSUE TITLE
[Documentation] Bad type on cpBodyGetSpace

### ISSUE THREAD

**Issue by mcclure** [slembcke/Chipmunk2D#176]
In the docs
https://chipmunk-physics.net/release/ChipmunkLatest-Docs/
is documented a function

    cpSpace cpBodyGetSpace(const cpBody *body)

But in cpBody.h the function is actually

    CP_EXPORT cpSpace* cpBodyGetSpace(const cpBody *body);

**Comment by mcclure** [comment]
Related issue. I find this in the documentation

> Alternate constructors for poly shapes. This version does not apply a transform nor does it create a convex hull. Verticies must be provided with a counter-clockwise winding.

        int cpPolyShapeGetNumVerts(cpShape *shape)

u misspelled "Vertices" and also this is not the correct name for the function. In the header is

    CP_EXPORT int cpPolyShapeGetCount(const cpShape *shape);

**Comment by slembcke** [comment]
Fixed, fixed, and fixed. Sorry this took too long!
