### ISSUE TITLE
possible dangling pointer access during cpSpaceFree()

### ISSUE THREAD

**Issue by nilput** [slembcke/Chipmunk2D#177]
hello, i'm following the hello world example
the library is compiled using msvc
```
    cpVect gravity = cpv(0, -100);
    cpSpace *space = cpSpaceNew();
    cpSpaceSetGravity(space, gravity);
    cpShape *ground = cpSegmentShapeNew(cpSpaceGetStaticBody(space), cpv(-20, 5), cpv(20, -5), 0);
    cpShapeSetFriction(ground, 1);
    cpSpaceAddShape(space, ground);
    cpFloat radius = 5;
    cpFloat mass = 1;
    cpFloat moment = cpMomentForCircle(mass, 0, radius, cpvzero);
    cpBody *ballBody = cpSpaceAddBody(space, cpBodyNew(mass, moment));
    cpBodyActivate(ballBody);
    cpBodySetPosition(ballBody, cpv(0, 15));
    cpShape *ballShape = cpSpaceAddShape(space, cpCircleShapeNew(ballBody, radius, cpvzero));
    cpShapeSetFriction(ballShape, 0.7);
    cpFloat timeStep = 1.0 / 60.0;
    //my code
    while (1) {
        cpVect pos = cpBodyGetPosition(ballBody);
        cpVect vel = cpBodyGetVelocity(ballBody);
        
        cpSpaceStep(space, timeStep);
        if ( .... )
            break;
    }

    // Clean up our objects and exit!
    cpShapeFree(ballShape);
    cpBodyFree(ballBody);
    cpShapeFree(ground);
    cpSpaceFree(space);
//^the freed ballBody pointer is dereferenced during this call
//the call stack is below
    return true;
```
The Callstack:
```
cpBodyIsSleeping(const cpBody * body=0xdddddddddddddddd)                                Line 133	

cpBodyActivate(cpBody * body=0x00000205e0646050)                                        Line 126	

cpBodyActivateWrap(cpBody * body=0x00000205e0646050, void * unused=0x0000000000000000)  Line 186	

cpSpaceEachBody(cpSpace * space=0x00000205e0645dd0,
                void(*)(cpBody *, void *) func=0x00007ff78fcd8040,
                void * data=0x0000000000000000)                                         Line 596	

cpSpaceDestroy(cpSpace * space=0x00000205e0645dd0)                                      Line 193	

cpSpaceFree(cpSpace * space=0x00000205e0645dd0)                                         Line 227	

chipmunk()
init()
WinMain()

```

the exact same problem seems to be mentioned in the forums thread: "iOS 10 and Chipmunk crash"

assuming i'm using the library correctly in terms of memory management, an ownership model should be selected, either the world owns the body, or the body is independent of the world, we might be left with one of few options:

* the body shouldn't be freed by itself, the world frees it
* the body notifies the world about its destruction which kind of implies searching the list of  dynamic pointers and nullifying that pointer (which has performance implications)
* at cpSpaceDestroy() no body pointer is accessed as any pointer can be already dangling

this is all assuming that it's a problem with the ownership model and that my usage of the library is correct, it could simply be a sillier bug :)

**Comment by slembcke** [comment]
Sorry that this didn't get answered for so long.

The problem is that you are freeing objects before removing them from the space. cpSpace doesn't take ownership of the objects, but does make assumptions that the referenced by it are valid.
