### ISSUE TITLE
Generating a shared library for Chipmunk2D

### ISSUE THREAD

**Issue by kraftpunk97** [slembcke/Chipmunk2D#179]
Hello. I'm working on a project that requires 2D game engine, and I was looking at Chipmunk2D as a candidate. This project is in Julia, and I will need to write wrappers for Chipmunk so that it can be made available to Julia users. Julia can call C code, but only if it's available as a shared library. I was wondering if Chipmunk can be made available as a shared library. I was looking through the Xcode project and the library available there is static. How can I generate a shared library for the same? Thanks.

**Comment by slembcke** [comment]
You can use the cmake files to produce a shared library. Alternatively, it's generally pretty easy to turn a static library into a shared one. Static libraries are all the code in an archived form so you can substitute the .a file for a list of .o files. I don't remember off the top of my head how to do it, but Google knows. ;) IIRC it's about as simple as `cc --shared my_library.a -o my_library.so`, but it varies by OS.
