### ISSUE TITLE
What about GLFW3

### ISSUE THREAD

**Issue by ldegen** [slembcke/Chipmunk2D#181]
Hi everyone,

there are several open issues (#143, #141, #115, ...) related to the fact that the demos currently depend on an obsolete version of GLFW.

There is also a PR #151 addressing this issue. The repository this PR was made from seems to be gone (or I am too stupid to use GitHub), but I was able to manually apply it to my local working copy without any major problem, and as far as I can see, all demos are working.

@slembcke in your comment to the PR you mention a feature branch (https://github.com/slembcke/Chipmunk2D/tree/glfw3), but that branch seems rather dead.
If it is any help, I can create a new PR based on PR #151. This should solve the build issues we are facing on Debian et al.

**Comment by ldegen** [comment]
I created a new PR #182. Please let me know if there is anything else I can do to help this getting sorted out.

**Comment by slembcke** [comment]
Re-posting my answer from the PR thread:
> GLFW3 is all well and good. I use it in several of my other projects. The problem is that this will only work for Linux users. I've been meaning to replace GLFW with something that builds out of the box on Mac and Windows too. Windows devs in particular are very... vocal... when things don't just work and I already have to deal with the disaster that is MSVC support. In the past I supported them by shipping GLFW binaries, and that's not really sustainable.
> 
> Anyway, I think there are probably 3 branches floating around at this point for GLFW3 support including one I made that replaced the GL2 renderer with a GL3.3 one. A couple weeks ago I started a Sokol app version, and I'm pretty happy with this since it's pretty trivial to distribute as source. I just have to finish rewriting the renderer, and I'm hoping to do that this week or next.

Anyway. Take a look at the Sokol branch if you are interested. I have some free time now-ish while we wait for our next full time contract to get signed. Fixing up Chipmunk is definitely on my TODO list as the ancient version of GLFW2 I ship for Mac doesn't stopped working a couple months ago too.
https://github.com/slembcke/Chipmunk2D/tree/sokol

**Comment by ldegen** [comment]
Ah, sorry, I was not aware of the cross-platform issues. Will have a look into this Sokol stuff then.
