### ISSUE TITLE
Racket FFI

### ISSUE THREAD

**Issue by srfoster** [slembcke/Chipmunk2D#183]
Hi,

I'm trying to create an updated FFI for Chipmunk 7 for the Racket language.  It's kind of working.  Something about callbacks seems broken.  

Here's the basic "Hello World" example from the Chipmunk docs.  I converted it to Racket, verified that it worked, then added some collision handler callbacks.  The `begin` callback seems to be broken, though.  

```
#lang racket

(require racket-chipmunk/lang/chipmunk-ffi)

(define gravity (cpv 0 -100))
(define space (cpSpaceNew))

(define handler (cpSpaceAddDefaultCollisionHandler space))

(set-cpCollisionHandler-cpCollisionBeginFunc!
  handler
  (lambda (a s d)
    (displayln "Begin")
    1))

(set-cpCollisionHandler-cpCollisionPreSolveFunc!
  handler
  (lambda (a s d)
    (displayln "PreSolve")
    1))

(set-cpCollisionHandler-cpCollisionPostSolveFunc!
  handler
  (lambda (a s d)
    (displayln "PostSolve")
    1))

(set-cpCollisionHandler-cpCollisionSeparateFunc!
  handler
  (lambda (a s d)
    (displayln "Separate")
    1))


(cpSpaceSetGravity space gravity)

(define ground 
  (cpSegmentShapeNew 
    (cpSpaceGetStaticBody space)
    (cpv -20 5)
    (cpv 20 -5)
    0.0))

(cpShapeSetFriction ground 1.0)
(cpSpaceAddShape space ground)

(define radius 5.0)
(define mass 1.0)

(define moment (cpMomentForCircle mass 0.0 radius (cpv 0 0)))

(define ballBody (cpSpaceAddBody space (cpBodyNew mass moment)))

(define ballShape (cpSpaceAddShape space (cpCircleShapeNew ballBody radius (cpv 0 0))))

(cpShapeSetFriction ballShape 0.7)

(define timeStep (/ 1 60))

(define time 0)
(let loop ()
  (set! time (+ time timeStep)) 

  (define pos (cpBodyGetPosition ballBody))
  (define vel (cpBodyGetVelocity ballBody))
  
  (cpSpaceStep space (real->double-flonum time))

  (when (< time 2) 
    (loop)))


(cpShapeFree ballShape)
(cpBodyFree ballBody)
(cpShapeFree ground)
(cpSpaceFree space)
```

The output is puzzling me:

```
PreSolve
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
PostSolve
Separate
```

A few odd things:

1) Why does "Begin" never print?
2) Why do "PostSolve" and "Separate" print so much more than "PreSolve"?

If it helps, here are my FFI declarations for these callbacks:

```
(define _cpCollisionBeginFunc
  (_fun _cpArbiter-pointer
        _cpSpace-pointer
        _pointer
        -> _cpBool))

(define _cpCollisionPreSolveFunc
  (_fun _cpArbiter-pointer
        _cpSpace-pointer
        _pointer
        -> _cpBool))

(define _cpCollisionPostSolveFunc
  (_fun _cpArbiter-pointer
        _cpSpace-pointer
        _pointer
        -> _cpBool
        ;The Chipmunk docs say it should be _void, but that was causing weird behavior too.
        ;I've tried it both ways
))

(define _cpCollisionSeparateFunc
  (_fun _cpArbiter-pointer
        _cpSpace-pointer
        _pointer
        -> _cpBool
        ;Made this non-void too, but only to be consistent
 ))

(define-cstruct _cpCollisionHandler
  ([typeA _cpCollisionType]
   [typeB _cpCollisionType]
   [cpCollisionBeginFunc     _cpCollisionBeginFunc]
   [cpCollisionPreSolveFunc  _cpCollisionPreSolveFunc]
   [cpCollisionPostSolveFunc _cpCollisionPostSolveFunc]
   [cpCollisionSeparateFunc  _cpCollisionSeparateFunc]
   [cpDataPointer            _cpDataPointer]))
```

Any ideas what I'm doing wrong?

**Comment by srfoster** [comment]
Actually, I just set up a Chipmunk dev environment and started doing some lower-level debugging.  I found that Chipmunk was sort of mixing up the handlers: What I was registering as

*  `presolve`, was getting stored in `hander->begin`,
*  `postsolve` was in `handler->preSolve`
*  `separate` was in `handler->postSolve`
* And my `begin` handler wasn't getting placed anywhere, as far as I could tell.  So the `handler->separate` was basically just the default.

That gave me the idea to alter the FFI declaration as follows:

```
(define-cstruct _cpCollisionHandler
  ([typeA _cpCollisionType]
   [typeB _cpCollisionType]
  
  [dummy _cpBool]

   [cpCollisionBeginFunc     _cpCollisionBeginFunc]
   [cpCollisionPreSolveFunc  _cpCollisionPreSolveFunc]
   [cpCollisionPostSolveFunc _cpCollisionPostSolveFunc]
   [cpCollisionSeparateFunc  _cpCollisionSeparateFunc]
   [cpDataPointer            _cpDataPointer]))
```

I don't know why, but that fixed it.  It really feels like a Racket FFI bug, and I'm going to reach out to the maintainers about that.

But if there's something weird about Chipmunk that might be causing this, I'd really like to know.  I'll leave the issue open until someone confirms that it's likely not on the Chipmunk end.

**Comment by mflatt** [comment]
I see that `_cpCollisionType` is defined in thoughtstem/racket-chipmunk as
```
(define _cpCollisionType _uint)
```
which is a 32-bit value on a 64-bit platform. 

But https://chipmunk-physics.net/release/ChipmunkLatest-API-Reference/group__basic_types.html says
```
typedef uintptr_t cpCollisionType
```
which is a 64-bit value on a 64-bit platform.

Does changing the definition of `_cpCollisionType` type to
```
(define _cpCollisionType _uintptr)
```
solve the problem?

**Comment by slembcke** [comment]
Hmm. Yeah sounds like it's just a case of getting the struct definition right.

Collision types are native pointer sized uints because it assumes you might want to use static object or class pointers as the type to take advantage of their uniqueness.

**Comment by srfoster** [comment]
Yes!  That solved the problem. :)  Thank you both.  And thanks for responding so quickly!
