### ISSUE TITLE
How can I make a segment that cannot be trespassed?

### ISSUE THREAD

**Issue by tuket** [slembcke/Chipmunk2D#195]
I'm making a small game with some walls.

![image](https://user-images.githubusercontent.com/4165974/86960736-42cd6680-c160-11ea-89ae-bc7b3fbee279.png)

The green walls are 4 static segments.

You can control the smiley face with the arrow keys. For the character movement, I'm just setting the speed of it's rigidBody.

The problem is that when you walk against the wall I can feel some resistance, but it's quite easy to trespass the wall. How should I implement the walls so they cannot be trespassed?

Thanks in advance.

**Comment by aismann** [comment]
Please use the chipmunk2D forum for this kind of questions.
Also add a little bit more information (source snippet) also there.

**Comment by tuket** [comment]
Okay, I thought the forum was abandoned by the looks of it. That's the reason I decided to ask here.
