### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by HVisMyLife** [slembcke/Chipmunk2D#215]
Can I use it with c++ code?
I know about c++ wrapers, but they are outdated...
If yes, how I can connect it to visual studio code? I'm on Arch btw. :)

**Comment by slembcke** [comment]
Yes, Chipmunk should compile fine as C99 or C++ code in most any recent compiler. It even has some mild C++ extension bits for the vector math. The only catch is that Chipmunk only provides a C style API. So it should work just fine, you just don't get most of the C++ specific syntax like constructors/destructors, polymorphic typing, and dot notation.

VSCode is great! Though I use Pop OS btw. (That just doesn't have the same ring, hehe) If you are already using CMake for your project you can just add Chipmunk as a subdirectory and CMake will do it's automagic thing. If you hate CMake (can't blame you... it's... weird) you can just build it and use the static library and headers instead. You can also just build it directly as part of your project if you want, but the only warning is that you must _not_ compile cpRobust.c with `-ffast-math` as those optimizations can cause really hard to debug collision issues.

**Comment by HVisMyLife** [comment]
Thanks for help, I will propably use it as static library now.
