### ISSUE TITLE
simulating rolling friction with Chipmunk2D for a top-down game

### ISSUE THREAD

**Issue by VictorQueiroz** [slembcke/Chipmunk2D#232]
I am developing a top-down 2D game and I'm using chipmunk for the physics, but I am stuck at the character movement due to the lack of support for rolling friction. The player continues moving after the impulse forever due to the lack of gravity, is there a common way to achieve what I want?

**Comment by aismann** [comment]
Set friction in the body

**Comment by VictorQueiroz** [comment]
@aismann if you mean to set friction on the player's body, I tried that, but it didn't have any effect. I am using `cpBodyApplyImpulseAtLocalPoint` to apply the impulse and make the player move, am I doing it wrong?

**Comment by aismann** [comment]
Let me See the source snippet olz

**Comment by VictorQueiroz** [comment]
@aismann I pushed my testing application here so you can check:

https://github.com/VictorQueiroz/Chipmunk2D-TopDown-Test

**Comment by aismann** [comment]
@VictorQueiroz 
Can you make a small video?

**Comment by VictorQueiroz** [comment]
@aismann what is the alternative to achieve what I want?

**Comment by VictorQueiroz** [comment]
@aismann here is the video you asked:

[2022-12-29 15-55-56.zip](https://github.com/slembcke/Chipmunk2D/files/10322918/2022-12-29.15-55-56.zip)

**Comment by VictorQueiroz** [comment]
I finally made it. I updated the project I sent you on GitHub. A comment from a guy in Reddit helped me fix it:

> I can't read c++ very well, but from what you describe it sounds like you haven't implemented drag yet. I like to implement it like this:
>
> velocity = velocity - (velocity * 0.25 * time.deltaTime)
>
> Velocity in this case is the movement vector of your object. You just lower it by a percentage per second until the movement is so little that it's basically stopped. However, it is good to note that it will never actually stop like this.
>
> You could implement drag a different way, it's really up to your preference.

I gently set it's velocity on every frame:

```cpp
cpVect vel = cpBodyGetVelocity(body.playable->controlBody);
vel = vel - (vel * 0.25 * dt);
cpBodySetVelocity(body.playable->controlBody, vel);
```
