### ISSUE TITLE
Segment query first, sometimes failing

### ISSUE THREAD

**Issue by DwiYI** [slembcke/Chipmunk2D#234]
Can anyone help me, why this happen ?.
I am following example from query demo but `cpSpaceSegmentQueryFirst `sometimes failing. 

What kind of possible problem has this caused?
![screen-recording-6-24-2023-10-56-00-am_AkNf3Zb5](https://github.com/slembcke/Chipmunk2D/assets/19425248/5631c661-40cb-4b48-adc0-7647ee78d2f7)

**Comment by aismann** [comment]
It works here

**Comment by DwiYI** [comment]
That's right, the demo is working fine. but not on my code. I don't know how to do debug that because example working fine. Do you know possible cause of that ?

**Comment by aismann** [comment]
Look at your code ;)

**Comment by DwiYI** [comment]
this is dart binding


  ```
late SegmentQueryInfo info;
  (Shape shape, SegmentQueryInfo info) segmentQueryFirst({required Vector2 start, required Vector2 end, required double radius, required ShapeFilter filter}) {
    var sh = _bindings.cpSpaceSegmentQueryFirst(_space, start.toCpVect().ref, end.toCpVect().ref, radius, filter._toPointer().ref, 
             info._segmentQueryInfo);
    return (Shape._fromPointer(sh), info);
  }
```

this is query code
```

 widget.game.physicUpdateAfter = (p0) {
      var (lq.Shape shape, lq.SegmentQueryInfo info) = widget.game.space.segmentQueryFirst(start: start, end: end, radius: 10, filter: shapeFilterAll);
      if (shape.isExist) {
        poi = info.point;
        nor = info.normal;
        alp = info.alpha;
        lineDraw1 = true;
        desc = 'Segment Query: Dist(${alp * (end - start).length}) Normal(${nor.x}, ${nor.y})';
      } else {
        lineDraw1 = false;
        alp = 1;
        desc = 'Segment Query (None)';
      }
    };
```

**Comment by aismann** [comment]
work this correct :` shape.isExist` ?

**Comment by DwiYI** [comment]
thats, only check against null,

**Comment by aismann** [comment]
add some debug outputs on your code.\
Hope this is helping you.

**Comment by aismann** [comment]
> thats, only check against null,

Thats seems not correct ;) the object isn't null

**Comment by DwiYI** [comment]
Thank you for your suggestion. The problem come from filter parameter. My code sending garbage value. I will close this.
