### ISSUE TITLE
The demo crashes whether it's built with gcc or visual studio

### ISSUE THREAD

**Issue by Lucas-Marcel** [slembcke/Chipmunk2D#235]
if i switch to another example it crashes.

**Comment by Lucas-Marcel** [comment]
It appears that it only works on debug mode.

**Comment by hbiblia** [comment]
Windows 11 las demostraciones se bloquean cuando los elementos tienen colisión

**Comment by slembcke** [comment]
I don't have a fix for this, and have barely had any time to work on it, but as a workaround you can do `space->sleepTimeThreshold = INFINITY` to disable object sleeping as a temporary workaround.
