### ISSUE TITLE
Is there formatting config/rules used on Chipmunk2D?

### ISSUE THREAD

**Issue by viblo** [slembcke/Chipmunk2D#247]
Is a automatic source formatter used to format the Chipmunk2D c code? And if so, which one and what rules?

(Reason for asking is whenever I make some small changes I want to use some formatter, but it seems like the code doesn't follow any of the default ones included with clang-format which result in a full reformat of all the code..)

**Comment by andykorth** [comment]
Scott doesn't use an automatic formatter, he does it by hand. It works well for formatting things like matrices and math, which autoformatters can mangle. Feel free to just match the format of nearby lines.

**Comment by viblo** [comment]
Thanks! I see, then I know. I suspected this, but thought it was best to ask anyway. Its easy to get used to auto formatting when coding in other languages :)
