### ISSUE TITLE
alloca.h: No such file or directory

### ISSUE THREAD

**Issue by slimsag** [slembcke/Chipmunk2D#84]
Compiling with MinGW produces the error:

`alloca.h: No such file or directory`

`chipmunk.h:32` reads:

```
#ifdef _WIN32
    // For alloca().
    #include <malloc.h>
#else
    #include <alloca.h>
#endif
```

But it should read:

```
#if defined(WIN32) || defined(__WIN32) || defined(__WIN32__)
    // For alloca().
    #include <malloc.h>
#else
    #include <alloca.h>
#endif
```

I didn't submit a pull request since the change is small.

**Comment by jhasse** [comment]
I can confirm this using MSYS 2 and Mingw-w64.

**Comment by TyOverby** [comment]
This is still broken.  Can I take this issue?

**Comment by einarkristjan** [comment]
Using VS2015 on Windows 10 64bit I fixed this issue with:

#ifdef _WIN32 || _WIN64

**Comment by blitz-research** [comment]
Can confirm this happens with mingw-64 on Windows 10 too.

WIN32 should be _WIN32.
