### ISSUE TITLE
Build failure in Windows (MinGW-W64) due to missing `<sys/sysctl.h>`

### ISSUE THREAD

**Issue by darkuranium** [slembcke/Chipmunk2D#99]
Chipmunk 7.0.0 fails to build in Windows.

The compiler used was MinGW-W64, and the reason appears to be a missing `<sys/sysctl.h>` include in `src/cpHastySpace.c`:

    [ 20%] Building C object src/CMakeFiles/chipmunk.dir/cpHastySpace.c.obj
    C:\Devel\build\Chipmunk-7.0.0\src\cpHastySpace.c:9:24: fatal error: sys/sysctl.h: No such file or directory
     #include <sys/sysctl.h>
                            ^
    compilation terminated.
    src\CMakeFiles\chipmunk.dir\build.make:342: recipe for target 'src/CMakeFiles/chipmunk.dir/cpHastySpace.c.obj' failed
    mingw32-make[2]: *** [src/CMakeFiles/chipmunk.dir/cpHastySpace.c.obj] Error 1
    CMakeFiles\Makefile2:76: recipe for target 'src/CMakeFiles/chipmunk.dir/all' failed
    mingw32-make[1]: *** [src/CMakeFiles/chipmunk.dir/all] Error 2
    makefile:116: recipe for target 'all' failed
    mingw32-make: *** [all] Error 2

**Comment by darkuranium** [comment]
I was able to work around this issue temporarily by adding the following around the `<sys/sysctl.h>` include in `src/cpHastySpace.c`:

```c
#ifndef _WIN32
#include <sys/sysctl.h>
#endif /* not _WIN32 */
```

I also had to link with a threading library, which I did this way (in `src/CMakeLists.txt`):

```cmake
# near the top
find_package(Threads)

# ...
# after the add_library() line:
target_link_libraries(chipmunk ${CMAKE_THREAD_LIBS_INIT})

# ...
# similar for `chipmunk_static`:
target_link_libraries(chipmunk_static ${CMAKE_THREAD_LIBS_INIT})
```

**Comment by ezavada** [comment]
Adding the threading library additions to src/CMakeLists.txt given breaks configuration on Mac OS X. You need to put those inside platform specific blocks:

    if(WIN32)
      ...
    endif(WIN32)

**Comment by ezavada** [comment]
They break on MSVC too. So:

    if(WIN32 && !MSVC)
      ...
    endif(WIN32 && !MSVC)

**Comment by darkuranium** [comment]
Apparently, this is also broken in some older versions of FreeBSD (`u_int` is apparently not present).

I find it odd that this would break on OS X, though; I thought cmake would handle that.

**Comment by darkuranium** [comment]
I'm also trying to resolve this more generically, instead of on a per-platform basis, at least in the code.

[Someone in the FreeBSD bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197852#c3) has suggested including `<unistd.h>` instead of `<sys/sysctl.h>`, and working in terms of that. @ezavada, could you perhaps check if his `<unistd.h>` solution (see the attached file) works in OS X? I don't have access to that operating system, myself.

**Comment by ezavada** [comment]
Sorry, I wasn't clear about the Mac OS X problem. The #include \<sys/sysctl.h> works fine. The problem on the Mac in the **find_package(Threads)** and **target_link_libraries(chipmunk ${CMAKE_THREAD_LIBS_INIT})**.

That said, #include <unistd.h> doesn't give the results you want:

    [  3%] Building C object src/CMakeFiles/chipmunk_static.dir/cpHastySpace.c.o
    /Users/ezavada/work/pdg/deps/chipmunk/src/cpHastySpace.c:323:3: warning: implicit declaration of function 'sysctlbyname' is invalid in C99
           [-Wimplicit-function-declaration]
                 sysctlbyname("hw.ncpu", &threads, &size, NULL, 0);

This is with 

    Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
    Target: x86_64-apple-darwin14.1.0

**Comment by darkuranium** [comment]
@ezavada: I know you meant the threading thing. And it's not just a replacement of the include; again, see the attached file in the previously-linked reply in the FreeBSD issue.

**Comment by fuguelike** [comment]
I had this problem compiling for Android. The following change to the includes in cpHastySpace should fix for all platforms:

//#include <sys/param.h >
//#include <sys/sysctl.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#else
#include <sys/sysconf.h>
#endif

**Comment by martell** [comment]
@slembcke : we over at msys2 have a fix for this 

https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-chipmunk/001-build-fix.patch
would you consider merging this patch :)

Many thanks
Martell

**Comment by ricardoquesada** [comment]
As @fuguelike  said, `<sys/sysctl.h>` is not present on Android. However, Android has `<linux/sysctl.h>`.
